---
title: "Dedup-Code-AnyData"
output: html_document
---

```{r, Load data}

#Load packages
library(readr)
library(stringr)
library(dplyr)
#install.packages("RecordLinkage")
library(RecordLinkage) #contains compare.dedup function
```

```{r CSV input}
#Insert new data as CSV 
#newdat <- read.csv("data.csv", header=TRUE)
```

```{r XML input}
#Insert new data direct from Endnote (XML)
library(XML)
library(RCurl)

xmldat<-xmlParse("DedupData_real/EpilepsySearch260318_export060819.xml")
x <-  getNodeSet(xmldat,'//record')

xpath2 <-function(x, ...){
    y <- xpathSApply(x, ...)
    y <- gsub(",", "", y)  # remove commas if using comma separator
    ifelse(length(y) == 0, NA,  paste(y, collapse=", "))
}
    
newdat <- data.frame(
Author = sapply(x, xpath2, ".//contributors/authors", xmlValue),
Year   = sapply(x, xpath2, ".//dates/year", xmlValue),
Journal = sapply(x, xpath2, ".//periodical/full-title", xmlValue),
DOI = sapply(x, xpath2, ".//electronic-resource-num", xmlValue),
Title = sapply(x, xpath2, ".//titles/title", xmlValue),
Pages = sapply(x, xpath2, ".//pages", xmlValue),
Volume = sapply(x, xpath2, ".//volume", xmlValue),
Number = sapply(x, xpath2, ".//number", xmlValue),
Abstract = sapply(x, xpath2, ".//abstract", xmlValue),
RecordID = sapply(x, xpath2, ".//rec-number", xmlValue),
SecondaryTitle = sapply(x, xpath2, ".//titles/secondary-title", xmlValue)
 )

newdat  <- newdat %>% 
 mutate(Journal=ifelse(is.na(Journal), paste(SecondaryTitle), paste(Journal)))

```

```{r Format Data}
newdatformatted<- newdat %>%
  select(Author, Title, Year, Journal, Abstract, DOI, Number, Pages, Volume, RecordID) 

newdatformatted$Author <- as.character(newdatformatted$Author)

newdatformatted <- newdatformatted %>%
  mutate(Author = ifelse(Author=="", "Unknown", Author)) %>%
  mutate(Author = ifelse(is.na(Author), "Unknown", Author)) %>%
  mutate(Author = ifelse(Author=="Anonymous", "Unknown", Author))

#Make all upper case
newdatformatted <- as.data.frame(sapply(newdatformatted, toupper))

##Get rid of punctuation and DOI Differences
toRemove <- c("HTTP://DX.DOI.ORG/", "DOI:", "DOI", "DOI: ")
for (tR in toRemove) {
  newdatformatted$DOI <- gsub(tR, "", newdatformatted$DOI)
}
newdatformatted["Title"] <- as.data.frame(sapply(newdatformatted["Title"], function(x) gsub("[[:punct:]]", "", x)))
newdatformatted["Year"] <- as.data.frame(sapply(newdatformatted["Year"], function(x) gsub("[[:punct:]]", "", x)))

newdatformatted <- unique(newdatformatted)

newdatformatted<-newdatformatted %>%
  filter(!is.na(RecordID))
```

```{r NA conversion}
newdatformatted<- newdatformatted %>%
  mutate(Author = ifelse(Author=="NA", NA, paste(Author))) %>%
  mutate(Year = ifelse(Year=="NA", NA, paste(Year))) %>%
  mutate(Title = ifelse(Title=="NA", NA, paste(Title))) %>%
  mutate(Number = ifelse(Number=="NA", NA, paste(Number))) %>%
  mutate(Volume = ifelse(Volume=="NA", NA, paste(Volume))) %>%
  mutate(Pages = ifelse(Pages=="NA", NA, paste(Pages))) %>%
  mutate(Abstract = ifelse(Abstract=="NA", NA, paste(Abstract))) %>%
  mutate(DOI = ifelse(DOI=="NA", NA, paste(DOI))) %>%
  mutate(Journal = ifelse(Journal=="NA", NA, paste(Journal)))
```

```{r}
##Run compare.dedup function and block by Title&Pages OR Title&Author OR Title&Abstract OR Title&DOI
newpairs = compare.dedup(newdatformatted, blockfld = list(c(2,8), c(1,2), c(2,5), c(2,6)), strcmp = TRUE, exclude= "RecordID")

#Create df of pairs
dfpairs <- as.data.frame(newpairs$pairs)
linkedpairs <- dfpairs
```

```{r}
#Run compare.dedup function and block by Author&Year&Pages OR Year&Pages&DOI 
newpairs2 = compare.dedup(newdatformatted, blockfld = list(c(1,3,8), c(3,8,6)), strcmp = TRUE, exclude= c("RecordID"))
#Create df of pairs
dfpairs2 <- as.data.frame(newpairs2$pairs)
linkedpairs2 <- dfpairs2
```

```{r}
#Run compare.dedup function and block by Year&Pages&Volume OR Year&Issue&Volume
newpairs3 = compare.dedup(newdatformatted, blockfld = list(c(3,8,9), c(3,7,9)), strcmp = TRUE, exclude= "RecordID")

#Create df of pairs
dfpairs3 <- as.data.frame(newpairs3$pairs)
linkedpairs3 <- dfpairs3
```

```{r}
#Run compare.dedup function and block by Author&Year OR Title&Year
newpairs4 = compare.dedup(newdatformatted, blockfld = list(c(1,3), c(3,2), c(2,9), c(2,4)), strcmp = TRUE, exclude= "RecordID")

dfpairs4 <- as.data.frame(newpairs4$pairs)

linkedpairs4 <- dfpairs4 
```

```{r, See Pairs and further filters}
SeePairs <- rbind(linkedpairs, linkedpairs2, linkedpairs3, linkedpairs4)

SeePairs <- SeePairs  %>%
  mutate(Author1 = newdat$Author[id1]) %>%
  mutate(Author2 = newdat$Author[id2]) 

SeePairs <- SeePairs %>%
  mutate(Title1 =newdat$Title[id1]) %>%
  mutate(Title2 = newdat$Title[id2]) %>%
  mutate(Abstract1 = newdat$Abstract[id1]) %>%
  mutate(Abstract2 = newdat$Abstract[id2]) %>%
  mutate(DOI1 =newdat$DOI[id1]) %>%
  mutate(DOI2 =newdat$DOI[id2])

SeePairs <- SeePairs  %>%
  mutate(Year1= newdat$Year[id1]) %>%
  mutate(Year2= newdat$Year[id2]) %>%
  mutate(Number1 = newdat$Number[id1]) %>%
  mutate(Number2 = newdat$Number[id2]) %>%
  mutate(Pages1 = newdat$Pages[id1]) %>%
  mutate(Pages2 = newdat$Pages[id2]) %>%
  mutate(Volume1 = newdat$Volume[id1]) %>%
  mutate(Volume2 = newdat$Volume[id2]) 

SeePairs <- SeePairs  %>%
  mutate(Journal1 = newdat$Journal[id1]) %>%
  mutate(Journal2 = newdat$Journal[id2]) %>%
  mutate(RecordID1= newdat$RecordID[id1]) %>%
  mutate(RecordID2 = newdat$RecordID[id2]) 

SeePairs <- SeePairs %>%
  select(id1, id2, Author1, Author2, Author, Title1, Title2, Title, Abstract1, Abstract2, Abstract, Year1, Year2, Year, Number1, Number2, Number, Pages1, Pages2, Pages, Volume1, Volume2, Volume, Journal1, Journal2, Journal, DOI1, DOI2, DOI, RecordID1, RecordID2)

SeePairs <- SeePairs %>%
  mutate(Abstract = ifelse(is.na(Abstract1) & is.na(Abstract2), 0, Abstract)) %>%
  mutate(Pages = ifelse(is.na(Pages1) & is.na(Pages2), 1, Pages)) %>%
  mutate(Volume = ifelse(is.na(Volume1) & is.na(Volume2), 1, Volume)) %>%
  mutate(Number = ifelse(is.na(Number1) & is.na(Number2), 1, Number)) %>%
  mutate(DOI = ifelse(is.na(DOI1) & is.na(DOI2), 0, DOI)) 
 

SeePairsFiltered <- SeePairs %>%
  filter(
           (Pages>0.8 & Volume>0.8 & Title>0.90 & Abstract>0.90 & Author>0.50 & Journal>0.6) | 
           (Pages>0.8 & Number>0.8 & Title>0.90 & Abstract>0.90 & Author>0.50 & Journal>0.6) | 
           (Volume >0.8 & Number>0.8 & Title>0.90 & Abstract>0.90 & Author>0.50  & Journal>0.6) | 
           
           (Volume >0.8 & Number>0.8 & Title>0.90 & Abstract>0.90 & Author>0.8) |
           (Volume>0.8 & Pages>0.8 & Title>0.90 & Abstract>0.9 & Author>0.8) |
           (Pages>0.8 & Number>0.8 & Title>0.90 & Abstract>0.9 & Author>0.8) |
           
           (DOI>0.95 & Author>0.75 & Title>0.9 & Volume >0.8) |
           
           (Title>0.80 & Abstract>0.90 & Volume>0.85 & Journal>0.65 & Author>0.9) | 
           (Title>0.90 & Abstract>0.80 & Volume>0.85 & Journal>0.65 & Author>0.9)|
           
           (Pages>0.8 & Volume>0.8 & Title>0.90 & Abstract>0.8 & Author>0.9 & Journal>0.75) |
           (Pages>0.8 & Number>0.8 & Title>0.90 & Abstract>0.80 & Author>0.9 & Journal>0.75) | 
           (Volume>0.8 & Number>0.8 & Title>0.90 & Abstract>0.8 & Author>0.9  & Journal>0.75) |
           
           (Title>0.9 & Author>0.9 & Abstract>0.9 & Journal >0.7)|
             
           (Pages>0.9 & Number>0.9 & Title>0.90 & Author>0.80 & Journal>0.6) | 
           (Number>0.9 & Volume>0.9 & Title>0.90 & Author>0.90 & Journal>0.6) | 
           (Pages>0.9 & Volume>0.9 & Title>0.90 & Author>0.80 & Journal>0.6) |
             
           (Pages>0.8 & Volume>0.8 & Title>0.90 & Author>0.80 & Journal>0.9) |
           (Number>0.8 & Volume>0.8 & Title>0.90 & Author>0.80 & Journal>0.9)|
           (Number>0.8 & Pages>0.8 & Title>0.90 & Author>0.80 & Journal>0.9))

SeePairs <- unique(SeePairs)
SeePairsFiltered <- unique(SeePairsFiltered) 

#Added part 18/04/19 due to issues with 2 part papers or those with very similar titles with same journal/author/year being considered duplicates (more of an issue for older studies)
  SeePairsFiltered<- SeePairsFiltered %>%
    filter(is.na(DOI)| DOI > 0.99 | DOI ==0 | DOI < 0.99 & Pages>0.9 & Abstract>0.9)
  
```

```{r}
SeePairsFiltered$Year1 <- as.numeric(as.character(SeePairsFiltered$Year1))
SeePairsFiltered$Year2 <- as.numeric(as.character(SeePairsFiltered$Year2))

YearsDiff <- SeePairsFiltered[which(SeePairsFiltered$Year1 != SeePairsFiltered$Year2),]
YearsNotVeryDiff1 <- YearsDiff[which(YearsDiff$Year1 == YearsDiff$Year2+1 ),]
YearsNotVeryDiff2 <- YearsDiff[which(YearsDiff$Year1 == YearsDiff$Year2-1 ),]

YearsNotVeryDiff <- rbind(YearsNotVeryDiff1, YearsNotVeryDiff2)
YearsNotVeryDiff <- unique(YearsNotVeryDiff)

YearsVeryDiff <- YearsDiff[which(!rownames(YearsDiff) %in% rownames(YearsNotVeryDiff)),]

ManualDedup <- YearsVeryDiff 

SeePairsFiltered <- SeePairsFiltered[which(!rownames(SeePairsFiltered) %in% rownames(YearsVeryDiff)),]

SeePairsFiltered <- unique(SeePairsFiltered)

SeePairsFiltered$RecordID1 <- as.character(SeePairsFiltered$RecordID1)
SeePairsFiltered$RecordID2 <- as.character(SeePairsFiltered$RecordID2)
```

```{r}
set.seed(123)
SeePairsCheckSample <- SeePairs[sample(500),]

#write.csv(SeePairsCheckSample, file="SeePairsCheckSample500.csv")
```

```{r}
dedupdat <- newdat
dedupdat$RecordID <- as.character(dedupdat$RecordID)

SeePairsToDedup <- SeePairsFiltered

#Keep latest year
linkedpairskeepyear1 <- SeePairsToDedup[which(as.numeric(SeePairsToDedup$Year1) > as.numeric(SeePairsToDedup$Year2)),]
removerefs2 <- unique(linkedpairskeepyear1$RecordID2)
SeePairsToDedup <- SeePairsToDedup[which(!rownames(SeePairsToDedup) %in% rownames(linkedpairskeepyear1)),]
dedupdat <- dedupdat[which(!dedupdat$RecordID %in% removerefs2),]

linkedpairskeepyear2 <- SeePairsToDedup[which(as.numeric(SeePairsToDedup$Year2) > as.numeric(SeePairsToDedup$Year1)),]
removerefs3 <- unique(linkedpairskeepyear2$RecordID1)
removerefs3unique <- removerefs3[!removerefs3 %in% removerefs2]
SeePairsToDedup <- SeePairsToDedup[which(!rownames(SeePairsToDedup) %in% rownames(linkedpairskeepyear2)),]
dedupdat <- dedupdat[which(!dedupdat$RecordID %in% removerefs3),]

linkedpairskeep1 <- SeePairsToDedup[which(is.na(SeePairsToDedup$Abstract2) & !is.na(SeePairsToDedup$Abstract1)),]
removerefs1 <- unique(linkedpairskeep1$RecordID2)
SeePairsToDedup <- SeePairsToDedup[which(!rownames(SeePairsToDedup) %in% rownames(linkedpairskeep1)),]
dedupdat <- dedupdat[which(!dedupdat$RecordID %in% removerefs1),]

#Keep 2 for all other references 
removedalreadyID <- c(removerefs2, removerefs3, removerefs1)
removedalreadyID <- unique(removedalreadyID)
removedalready <- c(rownames(linkedpairskeepyear2), rownames(linkedpairskeepyear1), rownames(linkedpairskeep1))

linkedpairskeep2 <- SeePairsToDedup[which(!rownames(SeePairsToDedup) %in% removedalready),]
removerefs4 <- unique(linkedpairskeep2$RecordID1)
SeePairsToDedup <- SeePairsToDedup[which(!rownames(SeePairsToDedup) %in% rownames(linkedpairskeep2)),]
dedupdat <- dedupdat[which(!dedupdat$RecordID %in% removerefs4),]

dedupdat <- unique(dedupdat)

checkremovedalreadyID <- c(removerefs1, removerefs2, removerefs3, removerefs4)
checkremovedalreadyID <-unique(checkremovedalreadyID)
  
dedupdat<-unique(dedupdat)
```

```{r}
removedrecords<- c(removerefs1, removerefs2, removerefs3, removerefs4)

Labelled_duplicates_epilepsy <-newdat %>%
  mutate(DuplicateStatus = ifelse(RecordID %in% removedrecords, "DuplicateToRemove", "KeepRecord"))

write.csv(Labelled_duplicates_epilepsy, "Labelled_duplicates_epilepsy.csv")
write.csv(dedupdat, "dedupdat.csv")
```



```{r}
#Easy inport to Endnote as tab-delimited file
  dedupEndnote <- dedupdat %>%
    mutate("Reference Type" = paste("Journal Article")) %>%
    mutate("Secondary Title" = Journal) %>%
    mutate(Label = RecordID) %>%
    select("Reference Type", Author, Title, "Secondary Title", Label, Volume, Pages, Number, DOI, Year, Abstract) 
  
  dedupEndnote$Author <- as.character(dedupEndnote$Author)
  dedupEndnote$Title <- as.character(dedupEndnote$Title)
  dedupEndnote$Volume <- as.character(dedupEndnote$Volume)
  dedupEndnote$Pages <- as.character(dedupEndnote$Pages)
  dedupEndnote$Number <- as.character(dedupEndnote$Number)
  dedupEndnote$DOI <- as.character(dedupEndnote$DOI)
  dedupEndnote$Abstract <- as.character(dedupEndnote$Abstract)
  dedupEndnote$Year <- as.character(dedupEndnote$Year)
  dedupEndnote$"Secondary Title" <- as.character(dedupEndnote$"Secondary Tile")
  dedupEndnote$Label <- as.character(dedupEndnote$Label)
  
  dedupEndnote <-insertRows(dedupEndnote, 1, new=matrix(names(dedupEndnote), nrow=1, ncol=11))
  
  colnames(dedupEndnote) <- c("*Generic", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ") 
```

```{r}
IDsMatched <- c(SeePairsFiltered$RecordID1, SeePairsFiltered$RecordID2)

MaybePairs <- SeePairs %>%
  filter(!RecordID1 %in% IDsMatched) %>%
   filter(!RecordID2 %in% IDsMatched) %>%
  filter(Title>0.80 & Author>0.75)

MaybePairs <- rbind(MaybePairs, ManualDedup)
MaybePairs <- unique(MaybePairs)  
```

```{r}
write.csv(dedupdat, file="DeduplicatedData.csv")
```

```


